### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-Cristinalorenzomontes#1]
Buen trabajo @Cristinalorenzomontes !

### Algunas pistas para acabarlo:

- [x] Mete los tipos en un ul + li
- [x] Mappear los tipos lo debemos hacer dentro del componente Pokemon, es su responsabilidad https://github.com/Adalab/modulo-3-evaluacion-intermedia-Cristinalorenzomontes/blob/master/src/components/PokeList.js#L16
- [x] Usa propTypes para comprobar el tipo de dato de las props

### Cuando tengas esto si quieres puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by Cristinalorenzomontes** [comment]
Miguel no me acordaba como se hacía nada así que con el vídeo de la corrección lo he vuelto a hacer todo, pero no se hacer ninguno de los bonus :s
También quería poner una clase distinta para que el color de la letra en la que especifica el tipo de pokemon fuese de distinto color, pero tampoco lo consigo, si tienes tiempo podemos verlo porfa?
